input_dir: "D:/Respaldo_media/copy_paste_all_iphone/202103__" #"C:/Users/matias/Pictures/iCloud Photos/Photos" #"c:/Users/matias/Desktop/iCloudMFernandezLakatos/prueba_in" #
output_dir: "D:/Respaldo_media/iPhone14v2" #"c:/Users/matias/Desktop/iCloudMFernandezLakatos/prueba_out" # 
# output_dir: "Apple iPhone/Internal Storage/202506_d"
ffmpeg_path: "C:/Users/matias/ffmpeg/bin/ffmpeg.exe"
ffprobe_path: "C:/Users/matias/ffmpeg/bin/ffprobe.exe"
env_file: "environmentVar.env"
log_file: "logs/processed_files.txt"
skip_already_processed: true
max_files_per_session: 2499
delete_after_processing: false
inspect_some_files: false
number_of_files_to_inspect: 3
logging:
  enabled: true
  log_file: logs/media_organizer.log
  log_level: INFO
comparar_directorios: true
